version: '3.3'
 
services:
  portainer:
    container_name: portainer
    image: portainer/portainer-ce:latest
    ports:
      - '9000:9000'
    networks:
      - traefik_reverse_proxy
    environment:
      - ENCRYPTION_KEY=SMDd#6eJ2w9f8fU86IE@N5grtgkM!
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.portainer.rule=Host(`portainer.elmakchi.ir`)"
      - "traefik.http.routers.portainer.entrypoints=websecure"
      - "traefik.http.routers.portainer.tls.certresolver=myresolver"
      - "traefik.http.services.portainer.loadbalancer.server.port=9000"
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
      - './portainer_data:/data'
    restart: unless-stopped
    
networks:
  traefik_reverse_proxy:
    external: true 